FDTN-301: Enabling JVM metrics in DD
flowcommerce/registry pull request #472
Opened 2022-01-19 13:43 UTC by Yatharth0045

2022-01-19 14:57 UTC, gheine requested changes
Some comments inline

2022-01-19 14:57 UTC, gheine commented on api/conf/base.conf
> +    host = "datadog-cluster-agent.datadog"
This should come from the environment, if available. Something like
host = "localhost"
host = ${?DD_AGENT_HOST}

2022-01-19 14:57 UTC, gheine commented on api/conf/base.conf
> +    port = 5005
Port should probably not be set and instead use the default

2022-01-19 14:57 UTC, gheine commented on api/conf/base.conf
>    datadog-reporter = ${cinnamon.chmetrics.statsd-reporter} {
this syntax looks weird. Can you link to the documentation please?

2022-01-20 08:27 UTC, Yatharth0045 commented on api/conf/base.conf
>    datadog-reporter = ${cinnamon.chmetrics.statsd-reporter} {
This is for the newer version. We can ignore this for now. @gheine

2022-01-20 08:47 UTC, Yatharth0045 commented on api/conf/base.conf
>    datadog-reporter = ${cinnamon.chmetrics.statsd-reporter} {
But here's the reference to the old version documentation
https://developer.lightbend.com/docs/telemetry/2.3.x/plugins/datadog/datadog.html
https://developer.lightbend.com/docs/telemetry/2.3.x/plugins/chmetrics/statsd.html#dogstatsd

2022-01-20 08:50 UTC, Yatharth0045 commented on api/conf/base.conf
> +    host = "datadog-cluster-agent.datadog"
Will do it after testing if this static conf works as expected

2022-01-20 08:51 UTC, merged